changing memory requirements for diseasePortal index

diff --git a/bin/buildAllIndexesSequentially b/bin/buildAllIndexesSequentially
--- a/bin/buildAllIndexesSequentially
+++ b/bin/buildAllIndexesSequentially
@@ -8,7 +8,7 @@
 
 # indexes with standard (2-4Gb) memory requirements
 
-for index in reference marker allele markerAnnotation mpAnnotation authorsAC journalsAC structureAC vocabTermAC cre creAlleleSystem creAssayResult gxdLitIndex markerPanesetImage image gxdResult gxdImagePane gxdDifferentialMarker diseasePortal diseasePortalAnnotation
+for index in reference marker allele markerAnnotation mpAnnotation authorsAC journalsAC structureAC vocabTermAC cre creAlleleSystem creAssayResult gxdLitIndex markerPanesetImage image gxdResult gxdImagePane gxdDifferentialMarker diseasePortalAnnotation
 do
 
 uptime
@@ -25,18 +25,18 @@ done
 
 # indexes with larger memory requirements
 
-#for index in sequence
-#do
+for index in diseasePortal
+do
 
-#uptime
-#echo "Beginning ${index}..."
+uptime
+echo "Beginning ${index}..."
 
-#./buildIndex ${index} 4 8
-#if [ $? -ne 0 ]; then
-#    echo "Failed on ${index}"
-#    exit 1
-#fi
-#echo "Finished ${index}..."
+./buildIndex ${index} 4 8
+if [ $? -ne 0 ]; then
+    echo "Failed on ${index}"
+    exit 1
+fi
+echo "Finished ${index}..."
 
 #done
 echo "Successfully completed"
