forgot to exit script on failure

diff --git a/bin/buildAllIndexesSequentially b/bin/buildAllIndexesSequentially
--- a/bin/buildAllIndexesSequentially
+++ b/bin/buildAllIndexesSequentially
@@ -6,7 +6,7 @@
 uptime
 
 echo "Building all indexes"
-./buildIndex all 2 6
+./buildIndex all 2 6 || { echo "building indexes failed"; exit 1; }
 
 #done
 echo "Successfully completed"
