added error checking and setting of exit code

diff --git a/bin/configure b/bin/configure
--- a/bin/configure
+++ b/bin/configure
@@ -57,6 +57,11 @@ HTTP_HOST=`nslookup ${SOLR_HOST} | grep "^Name" | awk '{print $2}'`
 
 DB_PASSWORD=`cat $6 | grep ":${DB_USER}:" | cut -d':' -f5`
 
+if [ "${DB_PASSWORD}" = "" ]; then
+	echo "Error: could not find database password"
+	exit 1
+fi
+
 BASE_URL="http://${HTTP_HOST}:${SOLR_PORT}/solr"
 
 cat config.props.template \
@@ -68,6 +73,12 @@ cat config.props.template \
 
 cd ..
 ./Install
+
+if [ $? -ne 0 ]; then
+	echo "Error: Install script failed"
+	cd ${currentDir}
+	exit 1
+fi
 
 # go back where we started
 cd ${currentDir}
diff --git a/bin/configureAndBuildAll b/bin/configureAndBuildAll
--- a/bin/configureAndBuildAll
+++ b/bin/configureAndBuildAll
@@ -57,4 +57,13 @@ fi
 # Generate the Solr indexes.
 
 ./configure ${SOLR_HOST} ${SOLR_PORT} ${PG_FE_DBSERVER} ${PG_FE_DBNAME} ${PG_FE_DBUSER} ${PG_FE_DBPASSWORDFILE}
+if [ $? -ne 0 ]; then
+	echo "Error: configure script failed"
+	exit 1
+fi
+
 ./buildAllIndexes > ${LOG_DIR}/${SOLR_HOST}.log
+if [ $? -ne 0 ]; then
+	echo "Error: buildAllIndexes script failed"
+	exit 1
+fi
